---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka-pv-0
  labels:
    type: local
    app: kafka
spec:
  storageClassName: ""
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/openshift/openshift.local.pv/pv-kafka-0"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka-pv-1
  labels:
    type: local
    app: kafka
spec:
  storageClassName: ""
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/openshift/openshift.local.pv/pv-kafka-1"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka-pv-2
  labels:
    type: local
    app: kafka
spec:
  storageClassName: ""
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/openshift/openshift.local.pv/pv-kafka-2"
