apiVersion: v1
kind: Template
metadata:
  name: kafka-pv
  annotations:
    "openshift.io/display-name": Kafka PVs
    description: Persistent volumes for Apache Kafka
    iconClass: icon-cogs
    tags: "kafka"
parameters:
- description: 
  name: PVPATH
  required: true
objects:  
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: kafka-pv
    labels:
      type: local
      app: kafka
  spec:
    storageClassName: ""
    capacity:
      storage: 50Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: "${PVPATH}/pv-kafka-data"
